export const TableHeaders = [
  "Order Id",
  "Kích Cỡ",
  "Đường kính(cm)",
  "Sườn(miếng)",
  "Salad(g)",
  "Số lượng Nước",
  "Thành tiền",
  "loại Pizza",
  "idVoucher",
  "Loại nước Uống",
  "Họ và tên",
  "Email",
  "Số điện thoại",
  "Địa chỉ",
  "Lời nhắn",
  "Trạng thái",
];

export const TableColumns = [
  "orderId",
  "kichCo",
  "duongKinh",
  "suon",
  "salad",
  "soLuongNuoc",
  "thanhTien",
  "loaiPizza",
  "idVourcher",
  "idLoaiNuocUong",
  "hoTen",
  "email",
  "soDienThoai",
  "diaChi",
  "loiNhan",
  "trangThai",
];
